apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: mcnew
  name: mcnew
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/mcnew
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mcnew
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mcnew
    spec:
      containers:
      - image: registry.eu-gb.bluemix.net/cminion/minecraft:0.08
        imagePullPolicy: IfNotPresent
        name: mcnew
        ports:
        - containerPort: 8080
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-08-03T17:50:22Z
    lastUpdateTime: 2017-08-03T17:50:22Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
