apiVersion: v1
kind: Service
metadata:
  labels:
    run: mcnew
  name: mcnew
  namespace: default
  selfLink: /api/v1/namespaces/default/services/mcnew
spec:
  clusterIP: 10.10.10.39
  ports:
  - nodePort: 31259
    port: 8080
    protocol: UDP
    targetPort: 8080
  selector:
    run: mcnew
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
